- name: Replacing config
  copy:
    src: ../files/ldap_config.ldif
    dest: /etc/ldap/slapd.d/cn=config/olcDatabase={1}mdb.ldif
    owner: root       
    group: root       
    mode: '0644' 

- name: Restarting slapd
  systemd:
    name: slapd
    state: restarted

- name: Create organization entry if it doesn't exist
  vars:
  community.general.ldap_entry:
    dn: "{{ ldap_base_dn }}"
    objectClass:
      - organization
      - dcObject
      - top
    attributes:
      o: "{{ ldap_organization }}"
      dc: "{{ ldap_dc }}"
    state: present
    bind_dn: "{{ ldap_admin_dn }}"
    bind_pw: "{{ ldap_admin_password }}"
    server_uri: "{{ ldap_uri }}"
