- name: Update apt cache
  apt:
    update_cache: yes

- name: Install OpenLDAP
  apt:
    name:
      - slapd
      - ldap-utils
      - python3-ldap
    state: present
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: Ensure slapd is running and enabled
  systemd:
    name: slapd
    state: started
    enabled: yes
